../rtl/fetch/instr_mem.sv
../rtl/fetch/pc.sv
../rtl/fetch/pc_plus4F.sv
../rtl/fetch/branch_predict/branch_predict_unit.sv
../rtl/fetch/branch_predict/BTB.sv
../rtl/fetch/branch_predict/PHT.sv
../rtl/fetch/branch_predict/GHR.sv
../rtl/decode/control_unit.sv
../rtl/decode/imm_gen.sv
../rtl/decode/reg_file.sv
../rtl/execute/branch_resolve_unit.sv
../rtl/execute/alu.sv
../rtl/execute/branch.sv
../rtl/execute/mux_alu_src.sv
../rtl/execute/mux_forward.sv
../rtl/memory/lsu/dmem.sv
../rtl/memory/lsu/lsu.sv
../rtl/pipeline/fetch_stage.sv
../rtl/pipeline/decode_stage.sv
../rtl/pipeline/execute_stage.sv
../rtl/register_pipeline/IFID_register.sv
../rtl/register_pipeline/IDEX_register.sv
../rtl/register_pipeline/EXMEM_register.sv
../rtl/register_pipeline/MEMWB_register.sv
../rtl/data_hazard.sv
../rtl/pipeline_main.sv
